DPC-924_Automation_Stage_for_SI_filter_tests

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -126,7 +126,7 @@ sign_apks:
   stage: "sign_builds"
   variables:
     GIT_STRATEGY: none
-  cache: []
+  cache: [ ]
   tags:
     - "apk_signer_apk-signing-2.uplink.eyeo.it"
   before_script:
@@ -278,3 +278,87 @@ functional_tests:
   rules:
     - if: '$FORCE_FUNCTIONAL == "true"'
     - if: '$CI_PIPELINE_SOURCE == "schedule"'
+
+samsung_filter_tests:
+  stage: automated_tests
+  interruptible: true
+  needs:
+    - build # we can run this on debug apk
+  tags:
+    - "ce11171b5399805a0c"
+  retry: 1
+  image: "registry.gitlab.com/eyeo/docker/appium:1.20.2"
+  allow_failure: true
+  variables:
+    GIT_STRATEGY: "none"
+    PLATFORM_VERSIONS: "9"
+    GIT_AUTOMATION_REPO: "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/eyeo/distpartners/samsung_automation"
+    GIT_AUTOMATION_BRANCH: "main"
+  before_script:
+    - apt-get -y update
+    - apt-get -y install openjdk-8-jdk git net-tools
+    - echo "Using android device with serial ${ANDROID_SERIAL}"
+    - adb devices
+    - adb shell getprop | egrep "ro.product.manufacturer|ro.product.model|ro.build.version.release|ro.vendor.build.version.sdk"
+  script:
+    - mkdir appium
+    - /root/entry_point.sh &> appium/appium.log &
+    - echo $! > appium_pid
+    - git clone --depth=1 $GIT_AUTOMATION_REPO si_automation
+    - cd si_automation
+    - git checkout ${GIT_AUTOMATION_BRANCH:-main}
+    - OTHER_TEST_APK=$(find / -name "*app-world-abp-debug.apk")
+    - CHROMEDRIVER_EXECUTABLE=$(find / -name "*chrdlin99")
+    - export OTHER_TEST_APK
+    - export CHROMEDRIVER_EXECUTABLE
+    - echo CHROMEDRIVER_EXECUTABLE $CHROMEDRIVER_EXECUTABLE
+    - echo OTHER_TEST_APK $OTHER_TEST_APK
+    - pwd
+    # Launch an instance of gradle for each bunch of tags we want to test
+    - netstat -tulpn
+    - set +e
+    - |
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do export PLATFORM_VERSION
+        echo Starting job for version ${PLATFORM_VERSION}
+        (APPIUM_HOST="127.0.0.1:4723" ./gradlew filterTests &> platform_version-${PLATFORM_VERSION}.log ; echo $? > result_${PLATFORM_VERSION}) &
+        pids="$pids $!"
+      done
+    - wait $pids
+    # Check for any failures and re-run them
+    - |
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do if [ -s target/rerun${PLATFORM_VERSION}.txt ] ; then
+          echo "Rerunning failed test cases for platform version ${PLATFORM_VERSION}"
+          mv target/rerun${PLATFORM_VERSION}.txt target/rerun.txt
+          ./gradlew rerunFailed
+          echo $? > result_${PLATFORM_VERSION}
+          rm -f target/rerun.txt
+        fi
+      done
+    # check the exit codes of all processes were 0
+    - |
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do test $(cat result_${PLATFORM_VERSION}) = 0
+      done
+  after_script:
+    - cd si_automation
+    - |
+      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+        do
+        echo "**********************************"
+        echo "Logs for tests with platform version ${PLATFORM_VERSION}"
+        echo "**********************************"
+        cat platform_version-${PLATFORM_VERSION}.log
+      done
+  rules:
+    - if: '$FORCE_SAMSUNG == "true"'
+    - if: '$CI_PIPELINE_SOURCE == "schedule"'
+  artifacts:
+    when: always
+    expire_in: "1 day"
+    paths:
+      - "si_automation/platform_version-*.log"
+      - "si_automation/result_*"
+      - "si_automation/target/"
+      - "appium"
