removing rerun

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -287,7 +287,7 @@ samsung_filter_tests:
     - adb devices
     - adb shell getprop | egrep "ro.product.manufacturer|ro.product.model|ro.build.version.release|ro.vendor.build.version.sdk"
   script:
-    - /root/entry_point.sh &> appium.log &
+    - CHROMEDRIVER_AUTODOWNLOAD=true /root/entry_point.sh &> appium.log &
     - echo $! > appium_pid
     - git clone $GIT_AUTOMATION_REPO si_automation
     - cd si_automation
@@ -310,16 +310,16 @@ samsung_filter_tests:
       done
     - wait $pids
     # Check for any failures and re-run them
-    - |
-      for PLATFORM_VERSION in $PLATFORM_VERSIONS
-        do if [ -s target/rerun${PLATFORM_VERSION}.txt ] ; then
-          echo "Rerunning failed test cases for platform version ${PLATFORM_VERSION}"
-          mv target/rerun${PLATFORM_VERSION}.txt target/rerun.txt
-          ./gradlew rerunFailed
-          echo $? > result_${PLATFORM_VERSION}
-          rm -f target/rerun.txt
-        fi
-      done
+#    - |
+#      for PLATFORM_VERSION in $PLATFORM_VERSIONS
+#        do if [ -s target/rerun${PLATFORM_VERSION}.txt ] ; then
+#          echo "Rerunning failed test cases for platform version ${PLATFORM_VERSION}"
+#          mv target/rerun${PLATFORM_VERSION}.txt target/rerun.txt
+#          ./gradlew rerunFailed
+#          echo $? > result_${PLATFORM_VERSION}
+#          rm -f target/rerun.txt
+#        fi
+#      done
     # check the exit codes of all processes were 0
     - |
       for PLATFORM_VERSION in $PLATFORM_VERSIONS
